# Use SDK image for restore steps
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS restore

WORKDIR /src

# Copy all source files
COPY . .

# Restore
RUN dotnet restore ./__ProjectName__/__ProjectName__.csproj

# Use the same image for development
FROM restore AS development

# Set environment variables
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_USE_POLLING_FILE_WATCHER=1

# Set working directory
WORKDIR /src/__ProjectName__

# Install EF tool and add it to PATH
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

# Watch for changes and restart app
ENTRYPOINT ["dotnet", "watch", "run", "--no-restore"]
