version: '3.8'

services:
  api:
    build:
      dockerfile: Api/Dockerfile.development
    restart: on-failure
    environment:
      # Use development data protection certificate
      - DATA_PROTECTION_CERTIFICATE_PATH=/app/certificates/data-protection-development.pfx
    volumes:
      # Mount development certificates directory
      - ./certificates:/app/certificates:ro
      # Enable hot reloading
      - ./backend:/src:delegated
      # Improve image build speed
      - /src/Api/obj
      - /src/Api/bin
      - /src/Shared/obj
      - /src/Shared/bin
      - /src/Accounts/obj
      - /src/Accounts/bin

  pgadmin:
    image: dpage/pgadmin4
    container_name: modmontemplate-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - db
    volumes:
      - ${VOLUMES_PATH}/pgadmin:/var/lib/pgadmin
