version: '3.8'

services:
  api:
    container_name: application-api
    image: application-api
    build:
      context: ./backend
      dockerfile: Api/Dockerfile
    restart: unless-stopped
    ports:
      - "${API_PORT}:80"
    environment:
      - DATABASE=Host=db;Username=${DB_USER};Password=${DB_PASSWORD};Database=${DB_NAME};
    depends_on:
      - db
      - broker

  db:
    container_name: application-db
    image: postgres:16
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data

  broker:
    container_name: application-broker
    image: rabbitmq:3.12.7
    ports:
      - "${BROKER_PORT}:5672"
      - "${BROKER_UI_PORT}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
    volumes:
      - ${BROKER_VOLUME_PATH}:/var/lib/rabbitmq
