version: '3.8'

services:
  api:
    build:
      dockerfile: Api/Dockerfile.development
    restart: on-failure
    environment:
      - DATA_PROTECTION_CERTIFICATE_PATH=/app/certificates/data-protection-development.pfx
    volumes:
      - ./certificates:/app/certificates:ro
      - ./backend:/src:delegated
      - /src/Api/obj
      - /src/Api/bin
      - /src/Accounts/obj
      - /src/Accounts/bin
      - /src/Shared/obj
      - /src/Shared/bin
