version: '3.8'

services:
  api:
    build:
      dockerfile: Api/Dockerfile.development
    restart: on-failure
    volumes:
      - ./backend:/src:delegated
      - /src/Api/obj
      - /src/Api/bin
      - /src/Accounts/obj
      - /src/Accounts/bin
      - /src/Shared/obj
      - /src/Shared/bin
