version: '3.8'

services:
  nginx:
    ports:
      - "8080:80"
    volumes:
      - ./docker-dev-volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  api:
    build:
      dockerfile: Api/Dockerfile.development
    restart: on-failure
    environment:
      # Use development data protection certificate
      - DATA_PROTECTION_CERTIFICATE_PATH=/app/certificates/data-protection-development.pfx
    volumes:
      - ./docker-dev-volumes/api/data-protection/certificates:/app/certificates:ro
      # Enable hot reloading
      - ./backend:/src:delegated
      # Improve image build speed
      - /src/Api/obj
      - /src/Api/bin
      - /src/Shared/obj
      - /src/Shared/bin
      - /src/Accounts/obj
      - /src/Accounts/bin
