services:
  api:
    build:
      dockerfile: Api/Dockerfile.dev
    restart: on-failure
    volumes:
      - ./backend/Api:/src/Api:delegated
      - api_obj:/src/Api/obj
      - api_bin:/src/Api/bin

volumes:
  api_obj:
  api_bin:
