FROM mcr.microsoft.com/dotnet/sdk:7.0 AS restore
WORKDIR /src
COPY ["Api/Api.csproj", "Api/"]
RUN dotnet restore "Api/Api.csproj"

FROM restore AS development
WORKDIR /src/Api

COPY ["Api/Api.csproj", "."]
RUN dotnet restore

COPY Api/ .
EXPOSE 80

ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_USE_POLLING_FILE_WATCHER=1

ENTRYPOINT ["dotnet", "watch", "run", "--no-restore"]
