services:
  api:
    build:
      dockerfile: Api/Dockerfile.development
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./backend/Api:/src/Api:delegated
      - /src/Api/obj
      - /src/Api/bin
