services:
  api:
    container_name: application-api
    image: application-api
    build:
      context: ./backend
      dockerfile: Api/Dockerfile
    restart: unless-stopped
    ports:
      - "${API_PORT}:80"
    environment:
      - DATABASE=Host=database;Username=${DB_USER};Password=${DB_PASSWORD};Database=${DB_NAME};
    depends_on:
      - database
      - message-broker
