version: '3.8'

services:

  frontend:
    container_name: application-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NODE_ENV=${ENV}

  backend:
    container_name: application-backend
    image: application-backend
    build:
      context: ./backend
      dockerfile: Api/Dockerfile.production
    ports:
      - "${BACKEND_PORT}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV}
      - Database=Host=database;Username=${DB_USER};Password=${DB_PASSWORD};Database=${DB_NAME};
    depends_on:
      - database
      - broker
    volumes:
      - ./backend/Api:/src/Api
      - /src/Api/obj
      - /src/Api/bin

  database:
    container_name: application-database
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data

  broker:
    container_name: application-broker
    image: rabbitmq:3.12.7
    ports:
      - "${BROKER_PORT}:5672"
      - "${BROKER_UI_PORT}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
    volumes:
      - ${BROKER_VOLUME_PATH}:/var/lib/rabbitmq
