# .env:
# API_ENV=Development
# API_PORT=5000
# DB_PORT=5435
# DB_USER=admin
# DB_PASSWORD=String1@
# DB_NAME=application
# DB_VOLUME_PATH=C:/ProgramData/docker-volumes/application/db
# RABBITMQ_VOLUME_PATH=C:/ProgramData/docker-volumes/application/rabbitmq
# RABBITMQ_PORT=5672

version: '3.8'

services:

  api:
    container_name: application-api
    image: application-api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "${API_PORT}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${API_ENV}
      - Database=Host=db;Username=${DB_USER};Password=${DB_PASSWORD};Database=${DB_NAME};
    depends_on:
      - db
      - rabbitmq
    networks:
      - application-net

  db:
    container_name: application-db
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    networks:
      - application-net

  rabbitmq:
    container_name: application-rabbitmq
    image: rabbitmq:3.12.7
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ${RABBITMQ_VOLUME_PATH}:/var/lib/rabbitmq
    networks:
      - application-net

networks:
  application-net:
    driver: bridge
