version: '3.8'

services:

  backend:
    build:
      dockerfile: Api/Dockerfile.development
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./backend/Api:/src/Api:delegated
      - /src/Api/obj
      - /src/Api/bin
