# Use a Node.js base image
FROM node:20.10.0

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json /app/

# Install dependencies
RUN npm install

# Copy the rest of the app's source code
COPY . /app

# Expose the port the app runs on
EXPOSE 4200

# Start the app using npm start
CMD ["npm", "start"]