# Use a Node.js base image
FROM node:20.10.0

# Set the working directory in the container
WORKDIR /app

# Create a non-root user
RUN useradd -m nonrootuser

# Copy package.json and package-lock.json (if available)
# As root, so that the files get copied with root permissions
COPY package*.json /app/

# Change ownership of all files in the /app directory
RUN chown -R nonrootuser:nonrootuser /app

# Switch to non-root user
USER nonrootuser

# Install dependencies
RUN npm install

# Copy the rest of the app's source code
COPY --chown=nonrootuser:nonrootuser . /app

# Expose the port the app runs on
EXPOSE 4200

# Start the app using npm start
CMD ["npm", "start"]