services:
  message-broker:
    container_name: application-message-broker
    image: rabbitmq:3.12.7
    ports:
      - "${MESSAGE_BROKER_PORT}:5672"
      - "${MESSAGE_BROKER_UI_PORT}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${MESSAGE_BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${MESSAGE_BROKER_PASSWORD}
    volumes:
      - ${MESSAGE_BROKER_VOLUME_PATH}:/var/lib/rabbitmq
