services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_SA_PASSWORD}
    volumes:
      - sql_data:/var/opt/mssql
    ports:
      - "1444:1433"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "${DB_SA_PASSWORD}", "-Q", "select 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  sql_data:
    driver: local